### ISSUE TITLE
How to limit the number of threads/cores used?

### ISSUE THREAD

**Issue by hugomailhot** [bennetimo/shrinkwrap#5]
I've been using shrinkwrap a lot. It's a true life-saver.

However when I use it my computer becomes unusable for a long time, since I need to transcode tens of gigs of footage, which takes hours, and all cores are leveraged for parallel processing.

![image](https://user-images.githubusercontent.com/5240492/79055859-fa141900-7c15-11ea-9f45-96db1a443839.png)

^ Easily 6-10 hours or this per motorcycle ride!

Ideally I'd like to be able to dedicate a custom amount of cores to transcoding in the background, while I go about my other tasks without sacrificing too much CPU resources.

I looked into [ffmpeg options](https://ffmpeg.org/ffmpeg.html#Generic-options) I could pass to `--ffmpeg-opts`, tried things I don't really understand but had the word `threads` in them, such as `filter_threads=4`, but I still see all cores being used.

Am I missing something?

**Comment by bennetimo** [comment]
Hey @hugomailhot, sorry for the really slow response, must have missed this one! You should be able to limit the number of cores used one level up at the docker level. By default docker will allow unlimited cpu resources to be consumed, but you can tweak that.

From your screenshot it looks like you have 8 cores, so if you wanted to allow a max of say, 4 cores, to shrinkwrap then you should be able to limit it by adding `--cpus="4"`. 

You should specify this with the other docker commands, i.e. at the beginning, not with the commands that are sent to shrinkwrap. Something like:

```
docker run --cpus="4" -v "$(pwd)":/files bennetimo/shrinkwrap:latest ...
```

See here for the different options available: https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler.

Hope that helps!

**Comment by hugomailhot** [comment]
TIL!

Thank you 😁
